import { useState, useEffect } from "react";
import { Card, FormField, Loader } from "../components";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0)
    return data.map((post) => <Card key={post._id} {...post} />);

  return <h2 className="mt-5 font-bold text-red-600 text-lg">{title}</h2>;
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
    };
  }, []);

  return (
    <section className="max-w-7xl mx-auto">
      {/* the heading texts */}
      <div className="select-none">
        <h1 className="font-bold font-playfair text-3xl">
          The Community Showcase
        </h1>
        <p className="mt-2 text-gray-500 max-w-lg text-base">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>

      {/* form and all  */}
      <div className="mt-16">
        <FormField />
      </div>

      <div className="mt-10">
        {/* in case of loading  */}
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {/* in case there is search text  */}
            {searchText && (
              <h2 className="text-xl mb-3 font-medium">
                Showing results for{" "}
                <span className="text-gray-700 font-bold">{searchText}</span>
              </h2>
            )}
            {/* or just show the results */}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={[]} title="No search results found" />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
